spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/virtual_life
        username: postgres
        password: password
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format-sql: true
        show-sql: true
        open-in-view: false